Repository kakao-tech-campus-2nd-step3/Team5_BE, pull requests merged in 2024-10, with the labels that each got.

#35 Age/Category enum 타입으로 변경
  src/main/java/ojosama/talkak/category/model/Category.java
  src/main/java/ojosama/talkak/category/model/CategoryType.java
  src/main/java/ojosama/talkak/category/model/MemberCategory.java
  src/main/java/ojosama/talkak/category/repository/CategoryRepository.java
  src/main/java/ojosama/talkak/member/dto/MyPageInfoRequest.java
  src/main/java/ojosama/talkak/member/dto/MyPageInfoResponse.java
  src/main/java/ojosama/talkak/member/model/Age.java
  src/main/java/ojosama/talkak/member/model/Member.java
  src/main/java/ojosama/talkak/member/service/MyPageService.java
  src/test/java/ojosama/talkak/member/service/MyPageServiceTest.java
Labels: Refactoring

#36 webConfig 관련 코드 common 패키지로 이동
  src/main/java/ojosama/talkak/common/config/WebClientConfig.java
  src/main/java/ojosama/talkak/common/util/WebClientUtil.java
  src/main/java/ojosama/talkak/video/service/VideoService.java
  src/main/java/ojosama/talkak/video/service/YoutubeService.java
Labels: Refactoring

#38 ErrorAssertions by ErrorCode 추가
  src/test/java/ojosama/talkak/common/exception/ExceptionAssertions.java
  src/test/java/ojosama/talkak/video/service/VideoServiceTest.java
Labels: Feature

#39 Upload and download
  src/main/java/ojosama/talkak/video/controller/VideoController.java
  src/main/java/ojosama/talkak/video/dto/VideoRequest.java
  src/main/java/ojosama/talkak/video/dto/VideoResponse.java
  src/main/java/ojosama/talkak/video/model/Video.java
  src/main/java/ojosama/talkak/video/service/AwsS3Service.java
Labels: Feature

#37 Google 로그인 구현
  build.gradle
  src/main/java/ojosama/talkak/TalkakApplication.java
  src/main/java/ojosama/talkak/auth/config/AuthProperties.java
  src/main/java/ojosama/talkak/auth/config/HandlerConfig.java
  src/main/java/ojosama/talkak/auth/config/JwtProperties.java
  src/main/java/ojosama/talkak/auth/config/SecurityConfig.java
  src/main/java/ojosama/talkak/auth/config/UtilConfig.java
  src/main/java/ojosama/talkak/auth/dto/GoogleUserDetails.java
  src/main/java/ojosama/talkak/auth/dto/OAuth2UserDetails.java
  src/main/java/ojosama/talkak/auth/dto/TokenResponse.java
  src/main/java/ojosama/talkak/auth/filter/SuccessHandler.java
  src/main/java/ojosama/talkak/auth/service/AuthService.java
  src/main/java/ojosama/talkak/auth/utils/JwtUtil.java
  src/main/java/ojosama/talkak/common/config/WebConfig.java
  src/main/java/ojosama/talkak/member/model/Member.java
  src/main/java/ojosama/talkak/member/repository/MemberRepository.java
  src/test/java/ojosama/talkak/auth/config/SecurityConfigTest.java
Labels: Feature, API

#45 마이페이지 리팩토링
  src/main/java/ojosama/talkak/category/domain/Category.java
  src/main/java/ojosama/talkak/category/domain/MemberCategory.java
  src/main/java/ojosama/talkak/category/repository/CategoryRepository.java
  src/main/java/ojosama/talkak/common/exception/GlobalExceptionHandler.java
  src/main/java/ojosama/talkak/member/controller/MyPageController.java
  src/main/java/ojosama/talkak/member/domain/Member.java
  src/main/java/ojosama/talkak/member/dto/MyPageInfoRequest.java
  src/main/java/ojosama/talkak/member/service/MyPageService.java
  src/test/java/ojosama/talkak/member/controller/MyPageControllerTest.java
  src/test/java/ojosama/talkak/member/service/MyPageServiceTest.java
Labels: Feature, TestCode, Refactoring

#48 영상기록 관련 엔티티, Repository, Service 구현
  src/main/java/ojosama/talkak/comment/service/CommentService.java
  src/main/java/ojosama/talkak/common/exception/code/VideoError.java
  src/main/java/ojosama/talkak/reaction/domain/Reaction.java
  src/main/java/ojosama/talkak/reaction/service/ReactionService.java
  src/main/java/ojosama/talkak/video/domain/Video.java
  src/main/java/ojosama/talkak/video/service/AwsS3Service.java
  src/main/java/ojosama/talkak/viewingRecord/domain/ViewingRecord.java
  src/main/java/ojosama/talkak/viewingRecord/repository/ViewingRecordRepository.java
  src/main/java/ojosama/talkak/viewingRecord/service/ViewingRecordService.java
Labels: Feature, Refactoring

#51 레퍼런스 기능 관련 테스트 코드 및 캐싱 확인
  .gitignore
  src/main/java/ojosama/talkak/category/repository/CategoryRepository.java
  src/main/java/ojosama/talkak/common/exception/code/VideoError.java
  src/main/java/ojosama/talkak/video/controller/VideoController.java
  src/main/java/ojosama/talkak/video/service/YoutubeService.java
  src/test/java/ojosama/talkak/video/service/YoutubeServiceTest.java
  src/test/resources/payload/get-youtube-category-shorts-success-response.json
  src/test/resources/payload/get-youtube-popular-shorts-success-response.json
Labels: Feature, TestCode

#50 추가 정보 입력
  src/main/java/ojosama/talkak/auth/config/SecurityServiceConfig.java
  src/main/java/ojosama/talkak/auth/service/AuthService.java
  src/main/java/ojosama/talkak/category/domain/MemberCategory.java
  src/main/java/ojosama/talkak/comment/domain/Comment.java
  src/main/java/ojosama/talkak/member/controller/MemberController.java
  src/main/java/ojosama/talkak/member/controller/MyPageController.java
  src/main/java/ojosama/talkak/member/domain/Member.java
  src/main/java/ojosama/talkak/member/dto/AdditionalInfoRequest.java
  src/main/java/ojosama/talkak/member/dto/AdditionalInfoResponse.java
  src/main/java/ojosama/talkak/member/dto/CategoryResponse.java
  src/main/java/ojosama/talkak/member/dto/MyPageInfoResponse.java
  src/main/java/ojosama/talkak/member/service/MemberService.java
  src/main/java/ojosama/talkak/reaction/domain/Reaction.java
  src/main/java/ojosama/talkak/video/domain/Video.java
  src/main/java/ojosama/talkak/video/service/VideoService.java
  src/test/java/ojosama/talkak/member/service/MemberServiceTest.java
  src/test/java/ojosama/talkak/video/service/VideoServiceTest.java
Labels: Feature, API

#54 마이페이지 리팩토링(추가)
  src/main/java/ojosama/talkak/category/domain/Category.java
  src/main/java/ojosama/talkak/member/controller/MemberController.java
  src/main/java/ojosama/talkak/member/service/MemberService.java
Labels: BugFix, Refactoring

#55 인증 정보 null 오류 수정
  src/main/java/ojosama/talkak/auth/config/FilterConfig.java
  src/main/java/ojosama/talkak/auth/config/SecurityConfig.java
  src/main/java/ojosama/talkak/auth/dto/OAuth2UserDetails.java
  src/main/java/ojosama/talkak/auth/filter/JwtAuthorizationFilter.java
  src/main/java/ojosama/talkak/auth/filter/SuccessHandler.java
  src/main/java/ojosama/talkak/auth/utils/JwtUtil.java
  src/main/java/ojosama/talkak/member/controller/MemberController.java
Labels: BugFix

#61 Swagger 세팅
  build.gradle
  src/main/java/ojosama/talkak/auth/config/SecurityConfig.java
  src/main/java/ojosama/talkak/common/config/SwaggerConfig.java
  src/main/java/ojosama/talkak/member/controller/MemberApiController.java
  src/main/java/ojosama/talkak/member/controller/MemberController.java
Labels: Enviroment

#65 마이페이지 API 스웨거 배포
  src/main/java/ojosama/talkak/member/controller/MemberApiController.java
  src/main/java/ojosama/talkak/member/controller/MemberController.java
  src/test/java/ojosama/talkak/member/service/MemberServiceTest.java
Labels: Deploy, API, Refactoring

#67 카테고리 초기 데이터 설정
  src/main/java/ojosama/talkak/category/config/CategoryInitializer.java
  src/main/java/ojosama/talkak/category/domain/Category.java
Labels: Feature

#68 webclient 에러 핸들링 및 비디오, s3 스웨거 추가
  src/main/java/ojosama/talkak/common/exception/code/WebClientError.java
  src/main/java/ojosama/talkak/common/util/WebClientUtil.java
  src/main/java/ojosama/talkak/video/controller/AwsS3ApiController.java
  src/main/java/ojosama/talkak/video/controller/AwsS3Controller.java
  src/main/java/ojosama/talkak/video/controller/VideoApiController.java
  src/main/java/ojosama/talkak/video/controller/VideoController.java
Labels: Feature

#71 week7 코드리뷰 제출
  build.gradle
  src/main/java/ojosama/talkak/auth/config/SecurityConfig.java
  src/main/java/ojosama/talkak/category/config/CategoryInitializer.java
  src/main/java/ojosama/talkak/category/domain/Category.java
  src/main/java/ojosama/talkak/common/config/SwaggerConfig.java
  src/main/java/ojosama/talkak/common/exception/code/WebClientError.java
  src/main/java/ojosama/talkak/common/util/WebClientUtil.java
  src/main/java/ojosama/talkak/member/controller/MemberApiController.java
  src/main/java/ojosama/talkak/member/controller/MemberController.java
  src/main/java/ojosama/talkak/video/controller/AwsS3ApiController.java
  src/main/java/ojosama/talkak/video/controller/AwsS3Controller.java
  src/main/java/ojosama/talkak/video/controller/VideoApiController.java
  src/main/java/ojosama/talkak/video/controller/VideoController.java
  src/test/java/ojosama/talkak/auth/config/SecurityConfigTest.java
  src/test/java/ojosama/talkak/member/service/MemberServiceTest.java
Labels: Review

#74 추천 알고리즘/Redis 구현 및 도커 적용
  .gitignore
  Dockerfile
  build.gradle
  src/main/java/ojosama/talkak/category/config/CategoryInitializer.java
  src/main/java/ojosama/talkak/category/domain/MemberCategory.java
  src/main/java/ojosama/talkak/member/domain/Member.java
  src/main/java/ojosama/talkak/member/dto/MyPageInfoResponse.java
  src/main/java/ojosama/talkak/member/service/MemberService.java
  src/main/java/ojosama/talkak/redis/HashConverter.java
  src/main/java/ojosama/talkak/redis/RedisConfig.java
  src/main/java/ojosama/talkak/redis/RedisService.java
  src/main/java/ojosama/talkak/redis/domain/EventQueue.java
  src/main/java/ojosama/talkak/redis/domain/Reactions.java
  src/main/java/ojosama/talkak/redis/domain/Scores.java
  src/main/java/ojosama/talkak/redis/domain/UserMeta.java
  src/main/java/ojosama/talkak/redis/domain/VideoInfo.java
  src/main/java/ojosama/talkak/redis/innerkey/EventQueueHashKey.java
  src/main/java/ojosama/talkak/redis/innerkey/ReactionHashKey.java
  src/main/java/ojosama/talkak/redis/innerkey/ScoresSetKey.java
  src/main/java/ojosama/talkak/redis/innerkey/UserMetaHashKey.java
  src/main/java/ojosama/talkak/redis/innerkey/VideoHashKey.java
  src/main/java/ojosama/talkak/redis/key/DefaultScoresKey.java
  src/main/java/ojosama/talkak/redis/key/EventQueueKey.java
  src/main/java/ojosama/talkak/redis/key/ReactionKey.java
  src/main/java/ojosama/talkak/redis/key/ScoresKey.java
  src/main/java/ojosama/talkak/redis/key/UserMetaKey.java
  src/main/java/ojosama/talkak/redis/key/VideoKey.java
  src/main/java/ojosama/talkak/redis/repository/EventQueueRepository.java
  src/main/java/ojosama/talkak/redis/repository/ReactionsRepository.java
  src/main/java/ojosama/talkak/redis/repository/ScoresRepository.java
  src/main/java/ojosama/talkak/redis/repository/UserMetaRepository.java
  src/main/java/ojosama/talkak/redis/repository/VideoInfoRepository.java
  src/main/java/ojosama/talkak/redis/service/RecommendationService.java
  src/test/java/ojosama/talkak/member/service/MemberServiceTest.java
  src/test/java/ojosama/talkak/redis/config/RecommendTestContainerConfig.java
  src/test/java/ojosama/talkak/redis/config/RedisTestContainerConfig.java
  src/test/java/ojosama/talkak/redis/service/RecommendationServiceTest.java
  src/test/java/ojosama/talkak/redis/service/RedisServiceTest.java
Labels: Feature, Enviroment, Deploy, TestCode
