Repository kakao-tech-campus-2nd-step3/Team5_BE, pull requests merged in 2024-11, with the labels that each got.

#77 조회수/좋아요수 동시성 제어 기능 추가
  src/main/java/ojosama/talkak/common/exception/code/ReactionError.java
  src/main/java/ojosama/talkak/reaction/service/ReactionService.java
  src/main/java/ojosama/talkak/redis/domain/Reactions.java
  src/main/java/ojosama/talkak/redis/domain/VideoInfo.java
  src/main/java/ojosama/talkak/redis/repository/ReactionsRepository.java
  src/main/java/ojosama/talkak/redis/repository/UserMetaRepository.java
  src/main/java/ojosama/talkak/redis/repository/VideoInfoRepository.java
  src/test/java/ojosama/talkak/redis/repository/VideoInfoConcurrencyTest.java
Labels: Feature

#80 영상 관련 기능 구현 및 조회수 및 좋아요 접근 로직 Redis로 이전
  src/main/java/ojosama/talkak/common/exception/code/VideoError.java
  src/main/java/ojosama/talkak/member/domain/Member.java
  src/main/java/ojosama/talkak/reaction/controller/ReactionController.java
  src/main/java/ojosama/talkak/redis/service/ReactionService.java
  src/main/java/ojosama/talkak/video/controller/VideoApiController.java
  src/main/java/ojosama/talkak/video/controller/VideoController.java
  src/main/java/ojosama/talkak/video/domain/Video.java
  src/main/java/ojosama/talkak/video/repository/VideoRepository.java
  src/main/java/ojosama/talkak/video/request/VideoCategoryRequest.java
  src/main/java/ojosama/talkak/video/response/MemberInfoResponse.java
  src/main/java/ojosama/talkak/video/response/VideoDetailsResponse.java
  src/main/java/ojosama/talkak/video/response/VideoInfoResponse.java
  src/main/java/ojosama/talkak/video/service/VideoService.java
Labels: Feature, API, Refactoring

#78 Base entity 추가
  src/main/java/ojosama/talkak/category/domain/Category.java
  src/main/java/ojosama/talkak/comment/domain/Comment.java
  src/main/java/ojosama/talkak/common/entity/BaseEntity.java
  src/main/java/ojosama/talkak/member/domain/Member.java
  src/main/java/ojosama/talkak/video/domain/Video.java
  src/main/java/ojosama/talkak/viewingRecord/domain/ViewingRecord.java
Labels: Refactoring

#82 Member id 포함된 생성자 제거 및 테스트 코드 변경
  src/main/java/ojosama/talkak/member/domain/Member.java
  src/test/java/ojosama/talkak/member/service/MemberServiceTest.java
Labels: Refactoring

#85 조회수 및 좋아요의 접근 메서드 Redis로 변경 및 리뷰 반영 리팩토링
  src/main/java/ojosama/talkak/common/exception/code/VideoError.java
  src/main/java/ojosama/talkak/video/controller/VideoController.java
  src/main/java/ojosama/talkak/video/domain/Video.java
  src/main/java/ojosama/talkak/video/response/VideoDetailsResponse.java
  src/main/java/ojosama/talkak/video/service/VideoService.java
Labels: Refactoring

#86 Video/Commennt 생성자 파라미터 Id값 제거
  src/main/java/ojosama/talkak/comment/domain/Comment.java
  src/main/java/ojosama/talkak/member/domain/Member.java
  src/main/java/ojosama/talkak/reaction/domain/Reaction.java
  src/main/java/ojosama/talkak/reaction/domain/ReactionId.java
  src/main/java/ojosama/talkak/reaction/repository/ReactionRepository.java
  src/main/java/ojosama/talkak/redis/domain/Reaction.java
  src/main/java/ojosama/talkak/redis/repository/ReactionsRepository.java
  src/main/java/ojosama/talkak/redis/service/ReactionService.java
  src/main/java/ojosama/talkak/video/domain/Video.java
  src/main/java/ojosama/talkak/video/service/VideoService.java
  src/main/java/ojosama/talkak/viewingRecord/domain/ViewingRecord.java
  src/main/java/ojosama/talkak/viewingRecord/repository/ViewingRecordRepository.java
  src/main/java/ojosama/talkak/viewingRecord/service/ViewingRecordService.java
  src/test/java/ojosama/talkak/comment/service/CommentServiceTest.java
  src/test/java/ojosama/talkak/member/service/MemberServiceTest.java
  src/test/java/ojosama/talkak/redis/repository/VideoInfoConcurrencyTest.java
  src/test/java/ojosama/talkak/redis/service/RecommendationServiceTest.java
Labels: BugFix

#95 Comment API 스웨거 적용
  src/main/java/ojosama/talkak/comment/controller/CommentApiController.java
  src/main/java/ojosama/talkak/comment/controller/CommentController.java
  src/main/java/ojosama/talkak/comment/service/CommentService.java
  src/main/java/ojosama/talkak/member/domain/Member.java
  src/main/java/ojosama/talkak/member/service/MemberService.java
Labels: Deploy

#98 마이페이지 수정 반영되지 않는 오류 해결
  build.gradle
  src/main/java/ojosama/talkak/member/service/MemberService.java
  src/test/java/ojosama/talkak/member/service/MemberServiceTest.java
Labels: BugFix, Enviroment

#97 데모 데이터 추가 및 영상 관련 테스트 작성
  src/main/java/ojosama/talkak/category/config/CategoryInitializer.java
  src/main/java/ojosama/talkak/common/config/DemoDataInitializer.java
  src/main/java/ojosama/talkak/video/domain/Video.java
  src/test/java/ojosama/talkak/common/config/DummyDataTest.java
  src/test/java/ojosama/talkak/video/service/MockVideoServiceTest.java
Labels: Feature, TestCode

#100 redis 연결 오류 해결
  .gitignore
  Dockerfile
  src/main/java/ojosama/talkak/common/config/DemoDataInitializer.java
  src/main/java/ojosama/talkak/common/config/RedisConfig.java
  src/test/java/ojosama/talkak/redis/config/RedisTestContainerConfig.java
  src/test/java/ojosama/talkak/redis/service/RecommendationServiceTest.java
Labels: BugFix, Deploy

#99 토큰 관리
  src/main/java/ojosama/talkak/auth/config/FilterConfig.java
  src/main/java/ojosama/talkak/auth/config/SecurityConfig.java
  src/main/java/ojosama/talkak/auth/config/SecurityServiceConfig.java
  src/main/java/ojosama/talkak/auth/controller/AuthApiController.java
  src/main/java/ojosama/talkak/auth/controller/AuthController.java
  src/main/java/ojosama/talkak/auth/dto/ReissueRequest.java
  src/main/java/ojosama/talkak/auth/filter/JwtAuthorizationFilter.java
  src/main/java/ojosama/talkak/auth/filter/SuccessHandler.java
  src/main/java/ojosama/talkak/auth/service/AuthService.java
  src/main/java/ojosama/talkak/auth/service/OAuth2Service.java
  src/main/java/ojosama/talkak/auth/utils/JwtUtil.java
  src/main/java/ojosama/talkak/common/exception/code/AuthError.java
  src/main/java/ojosama/talkak/common/util/RedisKeyUtil.java
  src/main/java/ojosama/talkak/member/domain/Member.java
Labels: Feature, API

#106 특정 영상 응답값에 영상 제목 추가
  src/main/java/ojosama/talkak/common/config/DemoDataInitializer.java
  src/main/java/ojosama/talkak/video/response/VideoDetailsResponse.java
Labels: Refactoring

#108 로그인 커스텀 및 로그아웃
  src/main/java/ojosama/talkak/auth/config/FilterConfig.java
  src/main/java/ojosama/talkak/auth/config/GoogleProperties.java
  src/main/java/ojosama/talkak/auth/config/SecurityConfig.java
  src/main/java/ojosama/talkak/auth/config/SecurityServiceConfig.java
  src/main/java/ojosama/talkak/auth/controller/AuthApiController.java
  src/main/java/ojosama/talkak/auth/controller/AuthController.java
  src/main/java/ojosama/talkak/auth/dto/LogoutResponse.java
  src/main/java/ojosama/talkak/auth/filter/AuthorizationCodeFilter.java
  src/main/java/ojosama/talkak/auth/service/AuthService.java
  src/main/java/ojosama/talkak/auth/service/OAuth2Service.java
  src/main/java/ojosama/talkak/auth/service/StatelessAuthorizationRequestRepository.java
Labels: Feature, API

#110 파이썬 서버 관련 api 수정
  src/main/java/ojosama/talkak/video/controller/VideoController.java
  src/main/java/ojosama/talkak/video/request/HighlightRequest.java
  src/main/java/ojosama/talkak/video/request/PythonDto.java
  src/main/java/ojosama/talkak/video/service/AwsS3Service.java
  src/main/java/ojosama/talkak/video/service/VideoService.java
Labels: Feature, Refactoring

#111 영상 불러오기 인증 필터 미적용 및 파라미터 타입 오류 해결
  build.gradle
  src/main/java/ojosama/talkak/auth/config/SecurityConfig.java
  src/main/java/ojosama/talkak/common/util/LocalDateTimeSerializer.java
  src/main/java/ojosama/talkak/video/controller/VideoApiController.java
  src/main/java/ojosama/talkak/video/controller/VideoController.java
  src/main/java/ojosama/talkak/video/response/VideoInfoResponse.java
Labels: BugFix

#109 추가 정보 입력 여부 필드 추가
  src/main/java/ojosama/talkak/auth/dto/OAuth2UserDetails.java
  src/main/java/ojosama/talkak/auth/dto/TokenResponse.java
  src/main/java/ojosama/talkak/auth/filter/SuccessHandler.java
  src/main/java/ojosama/talkak/auth/service/AuthService.java
  src/main/java/ojosama/talkak/member/domain/Member.java
Labels: API

#112 thumbnail extraction용 util함수 추가
  build.gradle
  src/main/java/ojosama/talkak/video/util/ThumbnailExtractor.java
  src/main/resources/thumbnails/.gitkeep
  src/main/resources/videos/.gitkeep
Labels: Feature

#113 특정 영상 불러오기 Swagger 오류 응답 수정
  src/main/java/ojosama/talkak/video/controller/VideoApiController.java
  src/main/java/ojosama/talkak/video/service/VideoService.java
Labels: Refactoring

#115 Fix: CORS 관련 origin 설정 수정
  src/main/java/ojosama/talkak/auth/config/SecurityConfig.java
Labels: BugFix

#114 썸네일 이미지 처리
  src/main/java/ojosama/talkak/video/controller/VideoController.java
  src/main/java/ojosama/talkak/video/domain/Video.java
  src/main/java/ojosama/talkak/video/service/AwsS3Service.java
  src/main/java/ojosama/talkak/video/service/VideoService.java
Labels: Refactoring

#116 유튜브 API 오류 해결 및 테스트용 토큰 발급 무제한 기능 추가
  src/main/java/ojosama/talkak/auth/service/AuthService.java
  src/main/java/ojosama/talkak/video/response/YoutubeApiResponse.java
Labels: BugFix, Deploy

#117 구글 프로필 조회 API
  src/main/java/ojosama/talkak/member/controller/MemberApiController.java
  src/main/java/ojosama/talkak/member/controller/MemberController.java
  src/main/java/ojosama/talkak/member/dto/OAuthProfileResponse.java
  src/main/java/ojosama/talkak/member/service/MemberService.java
  src/test/java/ojosama/talkak/member/service/MemberServiceTest.java
Labels: API

#118 액세스 토큰 재발급 로직 수정
  src/main/java/ojosama/talkak/auth/config/SecurityConfig.java
  src/main/java/ojosama/talkak/auth/controller/AuthApiController.java
  src/main/java/ojosama/talkak/auth/controller/AuthController.java
  src/main/java/ojosama/talkak/auth/filter/JwtAuthorizationFilter.java
  src/main/java/ojosama/talkak/auth/filter/SuccessHandler.java
  src/main/java/ojosama/talkak/auth/service/AuthService.java
  src/main/java/ojosama/talkak/auth/utils/JwtUtil.java
Labels: BugFix, API

#119 인증 skip 엔드포인트 jwt 필터에 적용되지 않도록 수정
  src/main/java/ojosama/talkak/auth/config/FilterConfig.java
  src/main/java/ojosama/talkak/auth/filter/JwtAuthorizationFilter.java
Labels: BugFix

#120 댓글 api content 속성을 추가하여 response 명시
  src/main/java/ojosama/talkak/comment/controller/CommentApiController.java
Labels: Refactoring

#123 토큰 검사 로직 수정
  src/main/java/ojosama/talkak/auth/filter/JwtAuthorizationFilter.java
  src/main/java/ojosama/talkak/common/exception/code/AuthError.java
Labels: BugFix

#126 Reaction API 잘못된 예외 처리 로직 수정
  src/main/java/ojosama/talkak/auth/filter/JwtAuthorizationFilter.java
  src/main/java/ojosama/talkak/comment/controller/CommentController.java
  src/main/java/ojosama/talkak/reaction/controller/ReactionController.java
  src/main/java/ojosama/talkak/reaction/service/ReactionService.java
Labels: BugFix

#132 JSON parse error 관련 리팩터링
  src/main/java/ojosama/talkak/video/controller/VideoApiController.java
  src/main/java/ojosama/talkak/video/controller/VideoController.java
  src/main/java/ojosama/talkak/video/request/HighlightRequest.java
  src/main/java/ojosama/talkak/video/service/VideoService.java
Labels: Refactoring

#133 /error 인가 허용 추가
  src/main/java/ojosama/talkak/auth/config/CustomAuthenticationEntryPoint.java
  src/main/java/ojosama/talkak/auth/config/SecurityConfig.java
  src/main/java/ojosama/talkak/auth/filter/JwtAuthorizationFilter.java
  src/main/java/ojosama/talkak/common/exception/code/AuthError.java
Labels: Feature

#140 Feat: @RequestParams 로 속성값 넘겨주는 api
  src/main/java/ojosama/talkak/video/controller/VideoController.java
Labels: Feature

#142 더 이상 사용하지 않는 API / 메서드 삭제
  src/main/java/ojosama/talkak/video/controller/VideoApiController.java
  src/main/java/ojosama/talkak/video/controller/VideoController.java
  src/main/java/ojosama/talkak/video/request/HighlightRequest.java
  src/main/java/ojosama/talkak/video/request/PythonDto.java
  src/main/java/ojosama/talkak/video/service/AwsS3Service.java
  src/main/java/ojosama/talkak/video/service/VideoService.java
Labels: Refactoring

#137 추가 정보 입력 e2e 테스트 추가
  src/test/java/ojosama/talkak/annotation/WithMockMember.java
  src/test/java/ojosama/talkak/annotation/WithMockMemberSecurityContextFactory.java
  src/test/java/ojosama/talkak/member/MemberE2ETest.java
Labels: TestCode

#138 영상 관련 테스트 코드 오류 해결
  src/test/java/ojosama/talkak/video/service/MockVideoServiceTest.java
Labels: TestCode

#143 CommentServiceTest 정상 동작하도록 테스트용 Id 삽입
  src/test/java/ojosama/talkak/comment/service/CommentServiceTest.java
  src/test/java/ojosama/talkak/member/service/MyPageTest.java
Labels: BugFix, TestCode

#144 Refactor: videoUrl 속성 값 추가
  src/main/java/ojosama/talkak/video/domain/Video.java
  src/main/java/ojosama/talkak/video/service/VideoService.java
Labels: Refactoring

#145 ReadME.md 작성
  .github/workflows/gradle.yml
  README.md
  build.gradle
  src/main/java/ojosama/talkak/auth/config/FilterConfig.java
  src/main/java/ojosama/talkak/auth/config/GoogleProperties.java
  src/main/java/ojosama/talkak/auth/config/SecurityConfig.java
  src/main/java/ojosama/talkak/auth/config/SecurityServiceConfig.java
  src/main/java/ojosama/talkak/auth/controller/AuthApiController.java
  src/main/java/ojosama/talkak/auth/controller/AuthController.java
  src/main/java/ojosama/talkak/auth/dto/LogoutResponse.java
  src/main/java/ojosama/talkak/auth/dto/OAuth2UserDetails.java
  src/main/java/ojosama/talkak/auth/dto/TokenResponse.java
  src/main/java/ojosama/talkak/auth/filter/AuthorizationCodeFilter.java
  src/main/java/ojosama/talkak/auth/filter/JwtAuthorizationFilter.java
  src/main/java/ojosama/talkak/auth/filter/SuccessHandler.java
  src/main/java/ojosama/talkak/auth/service/AuthService.java
  src/main/java/ojosama/talkak/auth/service/OAuth2Service.java
  src/main/java/ojosama/talkak/auth/service/StatelessAuthorizationRequestRepository.java
  src/main/java/ojosama/talkak/auth/utils/JwtUtil.java
  src/main/java/ojosama/talkak/category/domain/CategoryType.java
  src/main/java/ojosama/talkak/comment/controller/CommentApiController.java
  src/main/java/ojosama/talkak/comment/controller/CommentController.java
  src/main/java/ojosama/talkak/common/config/DemoDataInitializer.java
  src/main/java/ojosama/talkak/common/exception/code/AuthError.java
  src/main/java/ojosama/talkak/common/util/LocalDateTimeSerializer.java
  src/main/java/ojosama/talkak/member/controller/MemberApiController.java
  src/main/java/ojosama/talkak/member/controller/MemberController.java
  src/main/java/ojosama/talkak/member/domain/Member.java
  src/main/java/ojosama/talkak/member/dto/AdditionalInfoRequest.java
  src/main/java/ojosama/talkak/member/dto/ProfileResponse.java
  src/main/java/ojosama/talkak/member/service/MemberService.java
  src/main/java/ojosama/talkak/reaction/controller/ReactionApiController.java
  src/main/java/ojosama/talkak/reaction/controller/ReactionController.java
  src/main/java/ojosama/talkak/reaction/service/ReactionService.java
  src/main/java/ojosama/talkak/video/controller/VideoApiController.java
  src/main/java/ojosama/talkak/video/controller/VideoController.java
  src/main/java/ojosama/talkak/video/domain/Video.java
  src/main/java/ojosama/talkak/video/request/VideoRequest.java
  src/main/java/ojosama/talkak/video/response/VideoDetailsResponse.java
  src/main/java/ojosama/talkak/video/response/VideoInfoResponse.java
  src/main/java/ojosama/talkak/video/response/YoutubeApiResponse.java
  src/main/java/ojosama/talkak/video/service/AwsS3Service.java
  src/main/java/ojosama/talkak/video/service/VideoService.java
  src/main/java/ojosama/talkak/video/util/ThumbnailExtractor.java
  src/main/resources/thumbnails/.gitkeep
  src/main/resources/videos/.gitkeep
  src/test/java/ojosama/talkak/comment/service/CommentServiceTest.java
  src/test/java/ojosama/talkak/member/service/MemberServiceTest.java
  src/test/java/ojosama/talkak/member/service/MyPageTest.java
  src/test/java/ojosama/talkak/reaction/ReactionTest.java
Labels: Docs

#146 createVideo에 VideoInfo 추가
  src/main/java/ojosama/talkak/video/service/VideoService.java
  src/test/java/ojosama/talkak/video/service/MockVideoServiceTest.java
Labels: Refactoring

#147 Video 더미 데이터에 url 추가
  src/main/java/ojosama/talkak/common/config/DemoDataInitializer.java
  src/main/java/ojosama/talkak/video/domain/Video.java
Labels: Refactoring

#149 최종 코드 제출
  .github/workflows/gradle.yml
  README.md
  build.gradle
  src/main/java/ojosama/talkak/auth/config/FilterConfig.java
  src/main/java/ojosama/talkak/auth/config/GoogleProperties.java
  src/main/java/ojosama/talkak/auth/config/SecurityConfig.java
  src/main/java/ojosama/talkak/auth/config/SecurityServiceConfig.java
  src/main/java/ojosama/talkak/auth/controller/AuthApiController.java
  src/main/java/ojosama/talkak/auth/controller/AuthController.java
  src/main/java/ojosama/talkak/auth/dto/LogoutResponse.java
  src/main/java/ojosama/talkak/auth/dto/OAuth2UserDetails.java
  src/main/java/ojosama/talkak/auth/dto/TokenResponse.java
  src/main/java/ojosama/talkak/auth/filter/AuthorizationCodeFilter.java
  src/main/java/ojosama/talkak/auth/filter/JwtAuthorizationFilter.java
  src/main/java/ojosama/talkak/auth/filter/SuccessHandler.java
  src/main/java/ojosama/talkak/auth/service/AuthService.java
  src/main/java/ojosama/talkak/auth/service/OAuth2Service.java
  src/main/java/ojosama/talkak/auth/service/StatelessAuthorizationRequestRepository.java
  src/main/java/ojosama/talkak/auth/utils/JwtUtil.java
  src/main/java/ojosama/talkak/category/domain/CategoryType.java
  src/main/java/ojosama/talkak/comment/controller/CommentApiController.java
  src/main/java/ojosama/talkak/comment/controller/CommentController.java
  src/main/java/ojosama/talkak/common/config/DemoDataInitializer.java
  src/main/java/ojosama/talkak/common/exception/code/AuthError.java
  src/main/java/ojosama/talkak/common/util/LocalDateTimeSerializer.java
  src/main/java/ojosama/talkak/member/controller/MemberApiController.java
  src/main/java/ojosama/talkak/member/controller/MemberController.java
  src/main/java/ojosama/talkak/member/domain/Member.java
  src/main/java/ojosama/talkak/member/dto/AdditionalInfoRequest.java
  src/main/java/ojosama/talkak/member/dto/ProfileResponse.java
  src/main/java/ojosama/talkak/member/service/MemberService.java
  src/main/java/ojosama/talkak/reaction/controller/ReactionApiController.java
  src/main/java/ojosama/talkak/reaction/controller/ReactionController.java
  src/main/java/ojosama/talkak/reaction/service/ReactionService.java
  src/main/java/ojosama/talkak/video/controller/VideoApiController.java
  src/main/java/ojosama/talkak/video/controller/VideoController.java
  src/main/java/ojosama/talkak/video/domain/Video.java
  src/main/java/ojosama/talkak/video/request/VideoRequest.java
  src/main/java/ojosama/talkak/video/response/VideoDetailsResponse.java
  src/main/java/ojosama/talkak/video/response/VideoInfoResponse.java
  src/main/java/ojosama/talkak/video/response/YoutubeApiResponse.java
  src/main/java/ojosama/talkak/video/service/AwsS3Service.java
  src/main/java/ojosama/talkak/video/service/VideoService.java
  src/main/java/ojosama/talkak/video/util/ThumbnailExtractor.java
  src/main/resources/thumbnails/.gitkeep
  src/main/resources/videos/.gitkeep
  src/test/java/ojosama/talkak/annotation/WithMockMember.java
  src/test/java/ojosama/talkak/annotation/WithMockMemberSecurityContextFactory.java
  src/test/java/ojosama/talkak/comment/service/CommentServiceTest.java
  src/test/java/ojosama/talkak/member/MemberE2ETest.java
  src/test/java/ojosama/talkak/member/service/MemberServiceTest.java
  src/test/java/ojosama/talkak/member/service/MyPageTest.java
  src/test/java/ojosama/talkak/reaction/ReactionTest.java
  src/test/java/ojosama/talkak/video/service/MockVideoServiceTest.java
Labels: Deploy
