Repository kakao-tech-campus-2nd-step3/Team5_BE, pull requests merged in 2024-09, with the labels that each got.

#10 Env: 커스텀 예외 처리 추가
  src/main/java/ojosama/talkak/common/exception/ErrorResponse.java
  src/main/java/ojosama/talkak/common/exception/GlobalExceptionHandler.java
  src/main/java/ojosama/talkak/common/exception/TalKakException.java
  src/main/java/ojosama/talkak/common/exception/code/ErrorCode.java
  src/main/java/ojosama/talkak/common/exception/code/VideoError.java
Labels: Enviroment

#11 Feat: 나머지 엔티티 클래스 구현
  src/main/java/ojosama/talkak/category/model/Category.java
  src/main/java/ojosama/talkak/category/model/MemberCategory.java
  src/main/java/ojosama/talkak/category/model/MemberCategoryId.java
  src/main/java/ojosama/talkak/keyword/model/Keyword.java
  src/main/java/ojosama/talkak/keyword/model/VideoKeyword.java
  src/main/java/ojosama/talkak/keyword/model/VideoKeywordId.java
  src/main/java/ojosama/talkak/reaction/model/Reaction.java
  src/main/java/ojosama/talkak/reaction/model/ReactionId.java
Labels: Feature

#19 3주차 피드백 반영
  src/main/java/ojosama/talkak/common/exception/code/VideoError.java
  src/main/java/ojosama/talkak/video/config/WebClientConfig.java
  src/main/java/ojosama/talkak/video/controller/VideoController.java
  src/main/java/ojosama/talkak/video/dto/YoutubeUrlValidationAPIResponseDto.java
  src/main/java/ojosama/talkak/video/dto/YoutubeUrlValidationRequestDto.java
  src/main/java/ojosama/talkak/video/dto/YoutubeUrlValidationResponseDto.java
  src/main/java/ojosama/talkak/video/exception/YoutubeValidationException.java
  src/main/java/ojosama/talkak/video/service/VideoService.java
  src/main/java/ojosama/talkak/video/util/IdExtractor.java
  src/main/java/ojosama/talkak/video/util/WebClientUtil.java
  src/test/java/ojosama/talkak/video/service/VideoServiceTest.java
  src/test/java/ojosama/talkak/video/service/YouTubeApiIntegrationTest.java
  src/test/resources/payload/get-youtube-api-response.json
Labels: TestCode, Refactoring

#24 영상 업로드 구현
  build.gradle
  src/main/java/ojosama/talkak/common/config/WebConfig.java
  src/main/java/ojosama/talkak/video/config/S3Config.java
  src/main/java/ojosama/talkak/video/controller/AwsS3Controller.java
  src/main/java/ojosama/talkak/video/controller/VideoController.java
  src/main/java/ojosama/talkak/video/dto/AwsS3Request.java
  src/main/java/ojosama/talkak/video/dto/AwsS3Response.java
  src/main/java/ojosama/talkak/video/dto/YoutubeUrlValidationAPIResponse.java
  src/main/java/ojosama/talkak/video/dto/YoutubeUrlValidationRequest.java
  src/main/java/ojosama/talkak/video/dto/YoutubeUrlValidationResponse.java
  src/main/java/ojosama/talkak/video/service/AwsS3Service.java
  src/main/java/ojosama/talkak/video/service/VideoService.java
  src/test/java/ojosama/talkak/video/service/VideoServiceTest.java
  src/test/java/ojosama/talkak/video/service/YouTubeApiIntegrationTest.java
  src/test/resources/payload/get-youtube-api-fail-response.json
  src/test/resources/payload/get-youtube-api-success-response.json
Labels: Feature

#27 예외 및 request 로깅
  src/main/java/ojosama/talkak/TalkakApplication.java
  src/main/java/ojosama/talkak/common/aop/LoggingAspect.java
Labels: Enviroment

#28 유튜브 레퍼런스 기능 구현
  README.md
  build.gradle
  src/main/java/ojosama/talkak/category/repository/CategoryRepository.java
  src/main/java/ojosama/talkak/video/config/CacheConfig.java
  src/main/java/ojosama/talkak/video/controller/VideoController.java
  src/main/java/ojosama/talkak/video/dto/YoutubeApiResponse.java
  src/main/java/ojosama/talkak/video/dto/YoutubeCategoryRequest.java
  src/main/java/ojosama/talkak/video/service/YoutubeService.java
  src/main/resources/ehcache.xml
Labels: Feature

#29 댓글 / 좋아요 기능 Serivce 및 Controller 구현
  src/main/java/ojosama/talkak/comment/controller/CommentController.java
  src/main/java/ojosama/talkak/comment/model/Comment.java
  src/main/java/ojosama/talkak/comment/repository/CommentRepository.java
  src/main/java/ojosama/talkak/comment/service/CommentService.java
  src/main/java/ojosama/talkak/common/exception/code/CommentError.java
  src/main/java/ojosama/talkak/common/exception/code/ReactionError.java
  src/main/java/ojosama/talkak/member/model/Member.java
  src/main/java/ojosama/talkak/member/model/MembershipTier.java
  src/main/java/ojosama/talkak/reaction/controller/ReactionController.java
  src/main/java/ojosama/talkak/reaction/model/Reaction.java
  src/main/java/ojosama/talkak/reaction/service/ReactionService.java
  src/main/java/ojosama/talkak/video/model/Video.java
  src/test/java/ojosama/talkak/comment/service/CommentServiceTest.java
Labels: Feature, Refactoring

#30 마이페이지 기능 구현
  src/main/java/ojosama/talkak/category/model/Category.java
  src/main/java/ojosama/talkak/category/model/MemberCategory.java
  src/main/java/ojosama/talkak/category/repository/CategoryRepository.java
  src/main/java/ojosama/talkak/category/repository/MemberCategoryRepository.java
  src/main/java/ojosama/talkak/common/exception/code/CategoryError.java
  src/main/java/ojosama/talkak/common/exception/code/MemberError.java
  src/main/java/ojosama/talkak/member/controller/MyPageController.java
  src/main/java/ojosama/talkak/member/dto/MyPageInfoRequest.java
  src/main/java/ojosama/talkak/member/dto/MyPageInfoResponse.java
  src/main/java/ojosama/talkak/member/model/Age.java
  src/main/java/ojosama/talkak/member/model/Member.java
  src/main/java/ojosama/talkak/member/service/MyPageService.java
  src/test/java/ojosama/talkak/member/service/MyPageServiceTest.java
Labels: Feature, API
